Improve help message when called with no arguments & redirect to stderr.

diff --git a/pdf2imgpdf b/pdf2imgpdf
--- a/pdf2imgpdf
+++ b/pdf2imgpdf
@@ -95,7 +95,7 @@ shift $((OPTIND-1))
 
 # Make sure there’s an argument provided
 if [ -z "$1" ]; then
-  echo "Error: no filename or directory supplied."
+  echo "Error: no filename or directory supplied. Try 'pdf2imgpdf -h' for more information." >&2
   exit 1
 fi
 
